Repository honestbank/terraform-gcp-sql, pull requests merged in 2024-06, with the labels that each got.

#40 fix: Specify provider version upper limit [DEVOP-4407]
  Makefile
  modules/google_compute_global_address/README.md
  modules/google_compute_global_address/main.tf
  modules/google_compute_network/README.md
  modules/google_compute_network/main.tf
  modules/google_service_networking_connection/README.md
  modules/google_service_networking_connection/main.tf
  modules/google_sql_database/README.md
  modules/google_sql_database/main.tf
  modules/google_sql_database_instance/README.md
  modules/google_sql_database_instance/main.tf
  modules/google_sql_user/README.md
  modules/google_sql_user/main.tf
Labels: size/M

#42 fix: add attribute deletion_policy in the google_service_networking_connection to fix terratest failure| DEVOP-4496
  .github/workflows/checkov.yaml
  .github/workflows/checkov.yml
  .github/workflows/semantic-pr.yaml
  .pre-commit-config.yaml
  examples/create_mysql_instance_with_private_ip/main.tf
  examples/create_mysql_instance_with_private_ip/variables.auto.tfvars
  examples/mysql_instance_with_read_replica/main.tf
  examples/postgres_instance_with_read_replica/main.tf
  examples/postgres_instance_with_read_replica/variables.auto.tfvars
  modules/google_service_networking_connection/main.tf
  modules/google_service_networking_connection/variables.tf
  test/gcp_sql_test.go
Labels: size/L

#44 fix: Resolve Terratest Failure During Instance Deletion (21 Retries) | [DEVOP-4525]
  .github/workflows/terratest.yml
  test/gcp_sql_test.go
  test/go.mod
  test/go.sum
Labels: size/XL
